# Generated by Django 6.1 on 2026-08-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_core', '0007_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_components', to='school_core.subject')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('subject', 'name')},
            },
        ),
    ]
