# Generated by Django 6.1 on 2026-08-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_core', '0008_gradecomponent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradecomponent',
            options={'ordering': ['assessment', 'order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='gradecomponent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gradecomponent',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GradeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_assessments', to='school_core.subject')),
            ],
            options={
                'ordering': ['subject', 'order', 'id'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.AddField(
            model_name='gradecomponent',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='school_core.gradeassessment'),
        ),
        migrations.RemoveField(
            model_name='gradecomponent',
            name='subject',
        ),
    ]
