# Generated by Django 6.1 on 2026-08-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_core', '0009_alter_gradecomponent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد')], default='draft', max_length=20),
        ),
    ]
